apiVersion: v1
kind: Service
metadata:
  name: expressmeal-service
  namespace: dev-namespace
spec:
  selector:
    app: expressmeal-deployment
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30431
  type: NodePort
